spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


file:
  profileImg: /img/profileImg
  productImg: /img/productImg
  reviewImg: /img/reviewImg

env: server