spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

file:
  profileImg: \C:\Users\Hong\Desktop\seb40_main_013\server\img\profileImg\
  productImg: \C:\Users\Hong\Desktop\seb40_main_013\server\img\productImg\

env: server